apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: andrei-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard      